/**
 * Builds the standalone demo pages from the same templates the plugin uses.
 *
 *   node tools/build-static.mjs
 *
 * These pages never ship — the release workflow copies an explicit allowlist and
 * ignores the repo root. They exist so the calculator can be opened without a
 * WordPress install, and so Jan and his partners have something to click.
 *
 * The point of generating them is that templates/partials/*.html is the ONLY
 * copy of the panel markup. Edit a partial and both the plugin and these pages
 * change together. Never hand-edit the generated .html files at the repo root.
 *
 * The tab registry is read out of tire-pressure-calculator.php rather than
 * restated here, so labels and tab order can't drift either.
 *
 * The one thing this file does duplicate is the shell markup (tab nav + panel
 * wrappers) — see renderShell() below, which must stay in step with
 * templates/shell.php. It's a dozen lines; the 300+ lines that actually churn
 * live in the partials and are shared.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Which shortcode becomes which page.
const PAGES = {
  tire_pressure_calculator: { file: 'calculator.html', title: 'Tire Pressure Calculator' },
  tire_finder:              { file: 'finder.html',     title: 'Tire Finder' },
};

// ── Read the tab registry out of the plugin entry point ──────────────────────

/** Returns the text between the brackets of `define( 'NAME', [ ... ] );`. */
function extractDefineArray(src, name) {
  const start = src.indexOf(`define( '${name}'`);
  if (start === -1) throw new Error(`${name} not found in tire-pressure-calculator.php`);
  const open = src.indexOf('[', start);
  if (open === -1) throw new Error(`${name} is not an array literal`);
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']' && --depth === 0) return src.slice(open + 1, i);
  }
  throw new Error(`unbalanced brackets in ${name}`);
}

const unquote = (s) => s.replace(/\\'/g, "'").replace(/\\\\/g, '\\');

const php = readFileSync(join(ROOT, 'tire-pressure-calculator.php'), 'utf8');

/** slug → label */
const TAB_LABELS = Object.fromEntries(
  [...extractDefineArray(php, 'RHC_TPC_TAB_LABELS')
      .matchAll(/'((?:[^'\\]|\\.)*)'\s*=>\s*'((?:[^'\\]|\\.)*)'/g)]
    .map(([, slug, label]) => [unquote(slug), unquote(label)])
);

/** shortcode tag → [slug, ...] */
const SHORTCODES = Object.fromEntries(
  [...extractDefineArray(php, 'RHC_TPC_SHORTCODES')
      .matchAll(/'((?:[^'\\]|\\.)*)'\s*=>\s*\[([^\]]*)\]/g)]
    .map(([, tag, list]) => [
      unquote(tag),
      [...list.matchAll(/'((?:[^'\\]|\\.)*)'/g)].map((m) => unquote(m[1])),
    ])
);

// ── Render ───────────────────────────────────────────────────────────────────

const escapeHtml = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Mirrors templates/shell.php — keep the two in step. */
function renderShell(tabs) {
  const nav = tabs
    .map((slug, i) =>
      `  <button class="tab-btn${i === 0 ? ' active' : ''}" ` +
      `onclick="rhcTpcSwitchTab('${escapeHtml(slug)}', this)">${escapeHtml(TAB_LABELS[slug])}</button>`)
    .join('\n');

  const panels = tabs
    .map((slug, i) => {
      const body = readFileSync(join(ROOT, 'templates', 'partials', `tab-${slug}.html`), 'utf8');
      return `<div id="rhc-tab-${escapeHtml(slug)}" class="tab-panel${i === 0 ? ' active' : ''}">\n` +
             `  <div class="panel-inner">\n${body.trimEnd()}\n  </div>\n</div>`;
    })
    .join('\n\n');

  return `<div class="rhc-tpc">\n\n<div class="tab-nav">\n${nav}\n</div>\n\n${panels}\n\n</div><!-- /.rhc-tpc -->`;
}

function renderPage(title, tabs) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)} – Rene Herse Cycles</title>
<!-- GENERATED by tools/build-static.mjs — do not edit. Edit templates/partials/*.html instead. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="tire-pressure-calculator/assets/tire-pressure-calculator.css">
<style>
  /* Local preview only — not part of the plugin. */
  body { margin: 0; background: #f5f2ed; }
  .rhc-preview-bar {
    font: 500 12px/1 'Open Sans', sans-serif; letter-spacing: .04em; text-transform: uppercase;
    padding: 10px 16px; background: #2e2a26; color: #cfc7bd;
  }
  .rhc-preview-bar a { color: #fff; }
</style>
</head>
<body>
<div class="rhc-preview-bar">Local preview · <a href="index.html">All pages</a></div>
${renderShell(tabs)}
<script src="tire-pressure-calculator/assets/tire-pressure-calculator.js"></script>
</body>
</html>
`;
}

/** The landing page, so a third page can't leave a stale hand-written index. */
function renderIndex(entries) {
  const cards = entries
    .map(({ file, title, tag, tabs }) =>
      `  <li>
    <a href="${escapeHtml(file)}">${escapeHtml(title)}</a>
    <span class="tabs">${tabs.map((s) => escapeHtml(TAB_LABELS[s])).join(' · ')}</span>
    <code>[${escapeHtml(tag)}]</code>
  </li>`)
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Rene Herse Calculators – Local Preview</title>
<!-- GENERATED by tools/build-static.mjs — do not edit. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<style>
  body { margin: 0; background: #f5f2ed; color: #2e2a26;
         font-family: 'Open Sans', sans-serif; }
  .wrap { max-width: 640px; margin: 0 auto; padding: 64px 24px; }
  h1 { font-family: 'Playfair Display', serif; font-weight: 600; font-size: 32px; margin: 0 0 8px; }
  p.lede { color: #6b625a; font-size: 15px; line-height: 1.7; margin: 0 0 32px; }
  ul { list-style: none; margin: 0; padding: 0; }
  li { background: #fff; border: 1px solid #e3dcd3; border-radius: 6px;
       padding: 20px 24px; margin-bottom: 12px; }
  li a { font-size: 19px; font-weight: 600; color: #8c2f1f; text-decoration: none; }
  li a:hover { text-decoration: underline; }
  .tabs { display: block; color: #6b625a; font-size: 14px; margin-top: 6px; }
  code { display: block; margin-top: 10px; font-size: 12px; color: #8a8078; }
  footer { margin-top: 32px; color: #8a8078; font-size: 13px; line-height: 1.7; }
</style>
</head>
<body>
<div class="wrap">
  <h1>Rene Herse Calculators</h1>
  <p class="lede">Local preview of the WordPress plugin. Each page below corresponds to one
  shortcode; on the live site each is placed on its own page.</p>
  <ul>
${cards}
  </ul>
  <footer>Generated from the plugin templates by <code style="display:inline">tools/build-static.mjs</code>.
  These pages are for review only and are not part of the released plugin.</footer>
</div>
</body>
</html>
`;
}

const built = [];
for (const [tag, { file, title }] of Object.entries(PAGES)) {
  const tabs = SHORTCODES[tag];
  if (!tabs) throw new Error(`shortcode ${tag} is not in RHC_TPC_SHORTCODES`);
  const missing = tabs.filter((slug) => !TAB_LABELS[slug]);
  if (missing.length) throw new Error(`${tag}: no label for ${missing.join(', ')}`);
  writeFileSync(join(ROOT, file), renderPage(title, tabs));
  built.push({ tag, file, title, tabs });
  console.log(`wrote ${file}  [${tabs.join(', ')}]`);
}

writeFileSync(join(ROOT, 'index.html'), renderIndex(built));
console.log('wrote index.html');
